print()
print("Edgar gael Garcia camacho 1182: Examen.")
print()
# Programa #1
Lista=["Matematicas" , "Español" ,  "Ciencias" , "Inglés" , "Programación" ]

print(Lista)
print()
Matematicas=float(input("Ingresa La calificacíon de matematicas :"))
print()
Español=float(input("Ingresa la calificacíon de español :"))
print()
Ciencias=float(input("Ingresa la calificacíon de ciencias :"))
print()
Inglés=float(input("Ingresa la calificacíon de inglés :"))
print()
Programacíon=float(input("Ingresa la calificacíon de programación :"))
print()

print("Las asignaturas que debes repetir son :")
print()
Lista.remove("Matematicas")
Lista.remove("Programación")
print()
print(Lista)
